<?php
ini_set('display_errors', 1);
error_reporting(E_ALL);
require_once 'app/Core/Database.php';
$db = new \App\Core\Database();
try {
    $pdo = $db->connect();
    $actualizados = 0;
    $resumen_subestaciones = '<p style="margin-bottom: 8px;"><strong><i class="fas fa-stopwatch" style="color: #3b82f6; margin-right: 5px;"></i> Duración:</strong> 25 horas académicas</p>\n                <p style="margin-bottom: 12px;"><strong><i class="fas fa-certificate" style="color: #10b981; margin-right: 5px;"></i> Incluye:</strong> Certificado de participación con QR</p>\n                <p style="line-height: 1.5;">Curso orientado a planificar, ejecutar y documentar mantenimientos de subestaciones elÃ©ctricas, combinando contenido teÃ³rico y prÃ¡ctica en campo.</p>';
    $temas_subestaciones = '<ul>\n                                        <li>Mantenimiento correctivo, preventivo y predictivo</li>\n                                        <li>Tipos y partes de subestaciones elÃ©ctricas</li>\n                                        <li>Transformadores, seccionadores y fusibles</li>\n                                        <li>Equipos de protección personal y trajes ignÃ\xadfugos</li>\n                                        <li>Equipos de maniobra y reglas de seguridad</li>\n                                        <li>MediciÃ³n de aislamiento y relaciÃ³n de transformaciÃ³n</li>\n                                        <li>AnÃ¡lisis de aceite dielÃ©ctrico</li>\n                                        <li>Visitas tÃ©cnicas, informes y protocolos</li>\n                                        <li>Certificado de operatividad</li>\n                                        <li>Procedimientos de corte y puesta en marcha</li>\n                </ul>';
    $beneficios_subestaciones = '<ul>\n                    <li>Certificado de participacion con QR</li>\n                    <li>Material digital exclusivo</li>\n                    <li>Grupo de WhatsApp del curso</li>\n                    <li>Entregables técnicos y formatos</li>\n                    <li>Clases teóricas grabadas y/o en vivo</li>\n                    <li>Acceso al aula virtual por tiempo limitado</li>\n                    \n                    <li style="margin-top: 15px; list-style: none; padding-left: 0;">\n                        <h5 style="font-size: 1rem; color: #0f172a; font-weight: 700; margin-bottom: 10px;">ð\x9f\x9b\xa0ï¸\x8f Equipos y herramientas</h5>\n                        <ul style="padding-left: 0; margin-bottom: 0;">\n                                                <li style="margin-bottom: 5px;">MegÃ³metro digital de 5000V</li>\n                                                <li style="margin-bottom: 5px;">Kit extractor de aceite dielÃ©ctrico</li>\n                                                <li style="margin-bottom: 5px;">PÃ©rtigas de maniobra</li>\n                                                <li style="margin-bottom: 5px;">Revelador de tensión</li>\n                                                <li style="margin-bottom: 5px;">Pinza amperimÃ©trica</li>\n                                                <li style="margin-bottom: 5px;">Traje ignÃ\xadfugo</li>\n                                                <li style="margin-bottom: 5px;">Careta contra arco elÃ©ctrico</li>\n                                                <li style="margin-bottom: 5px;">Guantes dielÃ©ctricos</li>\n                                                <li style="margin-bottom: 5px;">Equipos de seguridad y seÃ±alizaciÃ³n</li>\n                                                <li style="margin-bottom: 5px;">Herramientas manuales</li>\n                        </ul>\n                    </li>\n                </ul>';
    $programacion_subestaciones = '<div class="schedule-box" style="margin-bottom: 15px;">\n                                        <h5>ð\x9f\x8c\x8e VIRTUAL Perú, Ecuador y otros paÃ\xadses</h5>\n                                        <ul style="margin-bottom: 0;">\n                                            <li><strong>18/08:</strong> Online - Zoom de 6:00 p.m. a 9:00 p.m.</li>\n                                            <li><strong>19/08:</strong> SesiÃ³n virtual asíncrona</li>\n                                            <li><strong>20/08:</strong> Online - Zoom de 6:00 p.m. a 9:00 p.m.</li>\n                                            <li><strong>21/08:</strong> SesiÃ³n virtual asíncrona</li>\n                                            <li><strong>22/08:</strong> Online - Zoom de 2:00 p.m. a 7:00 p.m.</li>\n                                        </ul>';
    $update = $pdo->prepare("UPDATE cursos SET resumen = ?, temas = ?, beneficios = ?, programacion = ? WHERE LOWER(nombre_curso) LIKE ?");
    $update->execute([$resumen_subestaciones, $temas_subestaciones, $beneficios_subestaciones, $programacion_subestaciones, '%subestaciones%']);
    $actualizados += $update->rowCount();

    $resumen_condensadores = '<p style="margin-bottom: 8px;"><strong><i class="fas fa-stopwatch" style="color: #3b82f6; margin-right: 5px;"></i> Duración:</strong> 25 horas académicas</p>\n                <p style="margin-bottom: 12px;"><strong><i class="fas fa-certificate" style="color: #10b981; margin-right: 5px;"></i> Incluye:</strong> Certificado de participación con QR</p>\n                <p style="line-height: 1.5;">Curso orientado a la compensaciÃ³n de energÃ\xada reactiva y a la mejora del factor de potencia en sistemas elÃ©ctricos industriales.</p>';
    $temas_condensadores = '<ul>\n                                        <li>EnergÃ\xada reactiva y triÃ¡ngulo de potencia</li>\n                                        <li>Sistemas inductivos y capacitivos</li>\n                                        <li>DeterminaciÃ³n y correcciÃ³n del factor de potencia</li>\n                                        <li>CÃ¡lculo de KVAR con compensaciÃ³n fija</li>\n                                        <li>CÃ¡lculo de KVAR con compensaciÃ³n automÃ¡tica</li>\n                                        <li>AnÃ¡lisis de KVAR.h en facturaciÃ³n elÃ©ctrica</li>\n                                        <li>Bancos de condensadores fijos y automÃ¡ticos</li>\n                                        <li>Diseño bajo normativa IEC</li>\n                                        <li>ReducciÃ³n de pÃ©rdidas y caÃ\xaddas de tensión</li>\n                                        <li>SelecciÃ³n de contactores, fusibles, conductores y reguladores</li>\n                                        <li>InstalaciÃ³n prÃ¡ctica de condensadores</li>\n                </ul>';
    $beneficios_condensadores = '<ul>\n                    <li>Certificado de participacion con QR</li>\n                    <li>Material digital exclusivo</li>\n                    <li>Grupo de WhatsApp del curso</li>\n                    <li>Entregables técnicos y formatos</li>\n                    <li>Clases teóricas grabadas y/o en vivo</li>\n                    <li>Acceso al aula virtual por tiempo limitado</li>\n                    \n                    <li style="margin-top: 15px; list-style: none; padding-left: 0;">\n                        <h5 style="font-size: 1rem; color: #0f172a; font-weight: 700; margin-bottom: 10px;">ð\x9f\x9b\xa0ï¸\x8f Equipos y herramientas</h5>\n                        <ul style="padding-left: 0; margin-bottom: 0;">\n                                                <li style="margin-bottom: 5px;">Condensadores cilÃ\xadndricos de 25 KVAR</li>\n                                                <li style="margin-bottom: 5px;">Kit de contactores para condensadores</li>\n                                                <li style="margin-bottom: 5px;">Interruptores termomagnÃ©ticos</li>\n                                                <li style="margin-bottom: 5px;">Controlador de factor de potencia</li>\n                                                <li style="margin-bottom: 5px;">Transformadores de corriente</li>\n                                                <li style="margin-bottom: 5px;">Herramientas manuales</li>\n                        </ul>\n                    </li>\n                </ul>';
    $programacion_condensadores = '<div class="schedule-box" style="margin-bottom: 15px;">\n                                        <h5>ð\x9f\x8c\x8e VIRTUAL Perú, Ecuador y otros paÃ\xadses</h5>\n                                        <ul style="margin-bottom: 0;">\n                                            <li><strong>01/09:</strong> En VIVO Zoom de 7:00 p.m. a 9:00 p.m.</li>\n                                            <li><strong>02/09:</strong> SesiÃ³n virtual asíncrona</li>\n                                            <li><strong>03/09:</strong> En VIVO Zoom de 7:00 p.m. a 9:00 p.m.</li>\n                                            <li><strong>04/09:</strong> SesiÃ³n virtual asíncrona</li>\n                                            <li><strong>05/09:</strong> En VIVO Zoom de 9:00 a. m. a 1:00 p. m.</li>\n                                        </ul>';
    $update = $pdo->prepare("UPDATE cursos SET resumen = ?, temas = ?, beneficios = ?, programacion = ? WHERE LOWER(nombre_curso) LIKE ?");
    $update->execute([$resumen_condensadores, $temas_condensadores, $beneficios_condensadores, $programacion_condensadores, '%condensadores%']);
    $actualizados += $update->rowCount();

    $resumen_analizador = '<p style="margin-bottom: 8px;"><strong><i class="fas fa-stopwatch" style="color: #3b82f6; margin-right: 5px;"></i> Duración:</strong> 25 horas académicas</p>\n                <p style="margin-bottom: 12px;"><strong><i class="fas fa-certificate" style="color: #10b981; margin-right: 5px;"></i> Incluye:</strong> Certificado de participación con QR</p>\n                <p style="line-height: 1.5;">Curso dirigido a quienes desean evaluar, registrar y analizar parÃ¡metros elÃ©ctricos y perturbaciones en redes de baja y media tensión.</p>';
    $temas_analizador = '<ul>\n                                        <li>Tipos de analizadores y normativa vigente</li>\n                                        <li>ParÃ¡metros elÃ©ctricos y perturbaciones</li>\n                                        <li>SelecciÃ³n e instalaciÃ³n de analizadores</li>\n                                        <li>Conexionado en tablero y campo</li>\n                                        <li>ConfiguraciÃ³n de eventos y parÃ¡metros</li>\n                                        <li>Tipos de conexión e intervalos de mediciÃ³n</li>\n                                        <li>ExtracciÃ³n y modelaciÃ³n de datos</li>\n                                        <li>ElaboraciÃ³n de informes técnicos</li>\n                                        <li>Taller con analizador My Ebox 1500 â\x80\x93 Circutor</li>\n                </ul>';
    $beneficios_analizador = '<ul>\n                    <li>Certificado de participacion con QR</li>\n                    <li>Material digital exclusivo</li>\n                    <li>Grupo de WhatsApp del curso</li>\n                    <li>Entregables técnicos y formatos</li>\n                    <li>Clases teóricas grabadas y/o en vivo</li>\n                    <li>Acceso al aula virtual por tiempo limitado</li>\n                    \n                    <li style="margin-top: 15px; list-style: none; padding-left: 0;">\n                        <h5 style="font-size: 1rem; color: #0f172a; font-weight: 700; margin-bottom: 10px;">ð\x9f\x9b\xa0ï¸\x8f Equipos y herramientas</h5>\n                        <ul style="padding-left: 0; margin-bottom: 0;">\n                                                <li style="margin-bottom: 5px;">Analizador de redes Circutor</li>\n                                                <li style="margin-bottom: 5px;">Analizador de redes Fluke o Metrel</li>\n                                                <li style="margin-bottom: 5px;">Traje ignÃ\xadfugo y careta contra arco elÃ©ctrico</li>\n                                                <li style="margin-bottom: 5px;">Interruptor y transformador de prueba</li>\n                                                <li style="margin-bottom: 5px;">Laptop, recomendable para el alumno</li>\n                                                <li style="margin-bottom: 5px;">Equipos de seguridad y seÃ±alizaciÃ³n</li>\n                                                <li style="margin-bottom: 5px;">Herramientas manuales</li>\n                        </ul>\n                    </li>\n                </ul>';
    $programacion_analizador = '<div class="schedule-box" style="margin-bottom: 15px;">\n                                        <h5>ð\x9f\x8c\x8e VIRTUAL Perú, Ecuador y otros paÃ\xadses</h5>\n                                        <ul style="margin-bottom: 0;">\n                                            <li><strong>17/08:</strong> Zoom de 6:00 p.m. a 8:00 p.m.</li>\n                                            <li><strong>18/08:</strong> SesiÃ³n virtual asíncrona</li>\n                                            <li><strong>20/08:</strong> Zoom de 6:00 p.m. a 8:00 p.m.</li>\n                                            <li><strong>22/08:</strong> Zoom de 9:00 a.m. a 1:00 p.m.</li>\n                                        </ul>';
    $update = $pdo->prepare("UPDATE cursos SET resumen = ?, temas = ?, beneficios = ?, programacion = ? WHERE LOWER(nombre_curso) LIKE ?");
    $update->execute([$resumen_analizador, $temas_analizador, $beneficios_analizador, $programacion_analizador, '%analizador%']);
    $actualizados += $update->rowCount();

    $resumen_canalizacion = '<p style="margin-bottom: 8px;"><strong><i class="fas fa-stopwatch" style="color: #3b82f6; margin-right: 5px;"></i> Duración:</strong> 16 horas académicas</p>\n                <p style="margin-bottom: 12px;"><strong><i class="fas fa-certificate" style="color: #10b981; margin-right: 5px;"></i> Incluye:</strong> Certificado de participación con QR</p>\n                <p style="line-height: 1.5;">Curso enfocado en la ejecuciÃ³n de canalizaciones elÃ©ctricas con tuberÃ\xadas Conduit para instalaciones residenciales, comerciales e industriales.</p>';
    $temas_canalizacion = '<ul>\n                                        <li>Fundamentos de canalización eléctrica</li>\n                                        <li>Tuberías EMT, IMC y Conduit flexible</li>\n                                        <li>Accesorios, conectores, cajas de paso y condulet</li>\n                                        <li>Interpretación de planos eléctricos</li>\n                                        <li>Trazado de rutas y metrado de materiales</li>\n                                        <li>Herramientas de corte, perforación y doblado</li>\n                                        <li>Anclajes, soportes, riel Unistrut y abrazaderas</li>\n                                        <li>Curvas de 90°, offset y bayoneta</li>\n                                        <li>Roscado de tubería IMC</li>\n                                        <li>Montaje de canalizaciones</li>\n                                        <li>Inspección, pruebas y mantenimiento</li>\n                </ul>';
    $beneficios_canalizacion = '<ul>\n                    <li>Certificado de participacion con QR</li>\n                    <li>Material digital exclusivo</li>\n                    <li>Grupo de WhatsApp del curso</li>\n                    <li>Entregables técnicos y formatos</li>\n                    <li>Clases teóricas grabadas y/o en vivo</li>\n                    <li>Acceso al aula virtual por tiempo limitado</li>\n                    \n                    <li style="margin-top: 15px; list-style: none; padding-left: 0;">\n                        <h5 style="font-size: 1rem; color: #0f172a; font-weight: 700; margin-bottom: 10px;">ð\x9f\x9b\xa0ï¸\x8f Equipos y herramientas</h5>\n                        <ul style="padding-left: 0; margin-bottom: 0;">\n                                                <li style="margin-bottom: 5px;">TuberÃ\xadas Conduit IMC de Â¾â\x80\x9d</li>\n                                                <li style="margin-bottom: 5px;">TuberÃ\xadas Conduit IMC de 1â\x80\x9d</li>\n                                                <li style="margin-bottom: 5px;">TuberÃ\xadas Conduit EMT de Â¾â\x80\x9d</li>\n                                                <li style="margin-bottom: 5px;">Doblador manual y doblador hidrÃ¡ulico</li>\n                                                <li style="margin-bottom: 5px;">Cortador manual</li>\n                                                <li style="margin-bottom: 5px;">Bandeja metÃ¡lica y cajas de pase</li>\n                                                <li style="margin-bottom: 5px;">Accesorios para anclaje</li>\n                                                <li style="margin-bottom: 5px;">Uniones, conectores, curvas y adaptadores</li>\n                                                <li style="margin-bottom: 5px;">Herramientas manuales</li>\n                        </ul>\n                    </li>\n                </ul>';
    $programacion_canalizacion = '<div class="schedule-box" style="margin-bottom: 15px;">\n                                        <h5>ð\x9f\x8c\x8e VIRTUAL Perú, Ecuador y otros paÃ\xadses (NO HAY POR EL MOMENTO)</h5>\n                                        <ul style="margin-bottom: 0;">\n                                            <li><strong>04/08:</strong> Zoom en VIVO de 7:00 p.m. a 9:00 p.m.</li>\n                                            <li><strong>05/08:</strong> SesiÃ³n virtual asíncrona</li>\n                                            <li><strong>06/08:</strong> Zoom en VIVO de 7:00 p.m. a 9:00 p.m.</li>\n                                            <li><strong>07/08:</strong> SesiÃ³n virtual asíncrona</li>\n                                            <li><strong>09/08:</strong> Zoom en VIVO de 8:00 a.m. a 12:00 p.m.</li>\n                                            <li><strong>09/08:</strong> Zoom en VIVO de 1:00 p.m. a 5:00 p.m.</li>\n                                        </ul>';
    $update = $pdo->prepare("UPDATE cursos SET resumen = ?, temas = ?, beneficios = ?, programacion = ? WHERE LOWER(nombre_curso) LIKE ?");
    $update->execute([$resumen_canalizacion, $temas_canalizacion, $beneficios_canalizacion, $programacion_canalizacion, '%canalizacion%']);
    $actualizados += $update->rowCount();

    $resumen_terminaciones = '<p style="margin-bottom: 8px;"><strong><i class="fas fa-stopwatch" style="color: #3b82f6; margin-right: 5px;"></i> Duración:</strong> 15 horas académicas</p>\n                <p style="margin-bottom: 12px;"><strong><i class="fas fa-certificate" style="color: #10b981; margin-right: 5px;"></i> Incluye:</strong> Certificado de participación con QR</p>\n                <p style="line-height: 1.5;">Curso orientado a aprender la correcta instalaciÃ³n de terminaciones en cables de media tensión, aplicando procedimientos técnicos, criterios de seguridad y buenas prácticas del sector.</p>';
    $temas_terminaciones = '<ul>\n                                        <li>Tipos de cables y niveles de tensión</li>\n                                        <li>Conductor, aislamiento, semiconductoras y pantalla metÃ¡lica</li>\n                                        <li>Aislamientos XLPE, HEPR y EPR</li>\n                                        <li>Terminaciones rectas, interiores, exteriores y tripolares hasta 36 kV</li>\n                                        <li>Componentes de una terminaciÃ³n</li>\n                                        <li>MediciÃ³n de aislamiento con megÃ³metro</li>\n                                        <li>Herramientas aisladas y equipos de protección personal</li>\n                                        <li>PrÃ¡ctica de terminaciones interior y exterior hasta 25 kV</li>\n                </ul>';
    $beneficios_terminaciones = '<ul>\n                    <li>Certificado de participacion con QR</li>\n                    <li>Material digital exclusivo</li>\n                    <li>Grupo de WhatsApp del curso</li>\n                    <li>Entregables técnicos y formatos</li>\n                    <li>Clases teóricas grabadas y/o en vivo</li>\n                    <li>Acceso al aula virtual por tiempo limitado</li>\n                    \n                    <li style="margin-top: 15px; list-style: none; padding-left: 0;">\n                        <h5 style="font-size: 1rem; color: #0f172a; font-weight: 700; margin-bottom: 10px;">ð\x9f\x9b\xa0ï¸\x8f Equipos y herramientas</h5>\n                        <ul style="padding-left: 0; margin-bottom: 0;">\n                                                <li style="margin-bottom: 5px;">Cilindro de gas GLP y boquilla de 2â\x80\x9d</li>\n                                                <li style="margin-bottom: 5px;">Kit de terminaciÃ³n termocontraÃ\xadble de uso exterior</li>\n                                                <li style="margin-bottom: 5px;">Cable de media tensión de 10 kV y/o 25 kV</li>\n                                                <li style="margin-bottom: 5px;">Herramientas manuales</li>\n                        </ul>\n                    </li>\n                </ul>';
    $programacion_terminaciones = '<div class="schedule-box" style="margin-bottom: 15px;">\n                                        <h5>ð\x9f\x8c\x8e VIRTUAL Perú, Ecuador y otros paÃ\xadses</h5>\n                                        <ul style="margin-bottom: 0;">\n                                            <li><strong>26/08:</strong> Zoom en VIVO de 6:00 p.m. a 8:00 p.m.</li>\n                                            <li><strong>27/08:</strong> SesiÃ³n virtual asíncrona</li>\n                                            <li><strong>29/08:</strong> Zoom en VIVO de 8:00 a.m. a 12:00 p.m.</li>\n                                        </ul>';
    $update = $pdo->prepare("UPDATE cursos SET resumen = ?, temas = ?, beneficios = ?, programacion = ? WHERE LOWER(nombre_curso) LIKE ?");
    $update->execute([$resumen_terminaciones, $temas_terminaciones, $beneficios_terminaciones, $programacion_terminaciones, '%terminaciones%']);
    $actualizados += $update->rowCount();

    $resumen_empalmes = '<p style="margin-bottom: 8px;"><strong><i class="fas fa-stopwatch" style="color: #3b82f6; margin-right: 5px;"></i> Duración:</strong> 15 horas académicas</p>\n                <p style="margin-bottom: 12px;"><strong><i class="fas fa-certificate" style="color: #10b981; margin-right: 5px;"></i> Incluye:</strong> Certificado de participación con QR</p>\n                <p style="line-height: 1.5;">Curso orientado a aprender la correcta instalaciÃ³n de empalmes en cables de media tensión, aplicando procedimientos técnicos, criterios de seguridad y buenas prácticas del sector.</p>';
    $temas_empalmes = '<ul>\n                                        <li>Tipos de cables y niveles de tensión</li>\n                                        <li>Conductor, aislamiento, semiconductoras y pantalla metÃ¡lica</li>\n                                        <li>Aislamientos XLPE, HEPR y EPR</li>\n                                        <li>Empalmes termocontraÃ\xadbles unipolares hasta 36 kV</li>\n                                        <li>Componentes y preparaciÃ³n del empalme</li>\n                                        <li>MediciÃ³n de aislamiento con megÃ³metro</li>\n                                        <li>Herramientas aisladas y equipos de protección personal</li>\n                                        <li>PrÃ¡ctica de empalmes termocontraÃ\xadbles hasta 25 kV</li>\n                </ul>';
    $beneficios_empalmes = '<ul>\n                    <li>Certificado de participacion con QR</li>\n                    <li>Material digital exclusivo</li>\n                    <li>Grupo de WhatsApp del curso</li>\n                    <li>Entregables técnicos y formatos</li>\n                    <li>Clases teóricas grabadas y/o en vivo</li>\n                    <li>Acceso al aula virtual por tiempo limitado</li>\n                    \n                    <li style="margin-top: 15px; list-style: none; padding-left: 0;">\n                        <h5 style="font-size: 1rem; color: #0f172a; font-weight: 700; margin-bottom: 10px;">ð\x9f\x9b\xa0ï¸\x8f Equipos y herramientas</h5>\n                        <ul style="padding-left: 0; margin-bottom: 0;">\n                                                <li style="margin-bottom: 5px;">Cilindro de gas GLP y boquilla de 2â\x80\x9d</li>\n                                                <li style="margin-bottom: 5px;">Kit de terminaciÃ³n termocontraÃ\xadble de uso exterior</li>\n                                                <li style="margin-bottom: 5px;">Cable de media tensión de 10 kV y/o 25 kV</li>\n                                                <li style="margin-bottom: 5px;">Herramientas manuales</li>\n                        </ul>\n                    </li>\n                </ul>';
    $programacion_empalmes = '<div class="schedule-box" style="margin-bottom: 15px;">\n                                        <h5>ð\x9f\x8c\x8e VIRTUAL Perú, Ecuador y otros paÃ\xadses</h5>\n                                        <ul style="margin-bottom: 0;">\n                                            <li><strong>26/08:</strong> Zoom en VIVO de 6:00 p.m. a 8:00 p.m.</li>\n                                            <li><strong>27/08:</strong> SesiÃ³n virtual asíncrona</li>\n                                            <li><strong>29/08:</strong> Zoom en VIVO de 1:00 p.m. a 5:00 p.m.</li>\n                                        </ul>';
    $update = $pdo->prepare("UPDATE cursos SET resumen = ?, temas = ?, beneficios = ?, programacion = ? WHERE LOWER(nombre_curso) LIKE ?");
    $update->execute([$resumen_empalmes, $temas_empalmes, $beneficios_empalmes, $programacion_empalmes, '%empalmes%']);
    $actualizados += $update->rowCount();

    $resumen_variadores = '<p style="margin-bottom: 8px;"><strong><i class="fas fa-stopwatch" style="color: #3b82f6; margin-right: 5px;"></i> Duración:</strong> 30 horas académicas</p>\n                <p style="margin-bottom: 12px;"><strong><i class="fas fa-certificate" style="color: #10b981; margin-right: 5px;"></i> Incluye:</strong> Certificado de participación con QR</p>\n                <p style="line-height: 1.5;">Curso orientado al conexionado, programaciÃ³n y puesta en marcha de variadores de velocidad utilizados en procesos industriales.</p>';
    $temas_variadores = '<ul>\n                                        <li>Interpretación de planos y manuales</li>\n                                        <li>Conexionado de variadores de velocidad</li>\n                                        <li>Configuración y operación en modo local y remoto</li>\n                                        <li>Programación y puesta en marcha de variadores Schneider</li>\n                                        <li>Programación y puesta en marcha de variadores Danfoss</li>\n                                        <li>Programación y puesta en marcha de variadores ABB</li>\n                                        <li>Programación y puesta en marcha de variadores Delta</li>\n                                        <li>Programación y puesta en marcha de variadores Siemens</li>\n                                        <li>Programación y puesta en marcha de variadores Allen Bradley</li>\n                </ul>';
    $beneficios_variadores = '<ul>\n                    <li>Certificado de participacion con QR</li>\n                    <li>Material digital exclusivo</li>\n                    <li>Grupo de WhatsApp del curso</li>\n                    <li>Entregables técnicos y formatos</li>\n                    <li>Clases teóricas grabadas y/o en vivo</li>\n                    <li>Acceso al aula virtual por tiempo limitado</li>\n                    \n                    <li style="margin-top: 15px; list-style: none; padding-left: 0;">\n                        <h5 style="font-size: 1rem; color: #0f172a; font-weight: 700; margin-bottom: 10px;">ð\x9f\x9b\xa0ï¸\x8f Equipos y herramientas</h5>\n                        <ul style="padding-left: 0; margin-bottom: 0;">\n                                                <li style="margin-bottom: 5px;">6 motores elÃ©ctricos trifÃ¡sicos de Â¼ HP</li>\n                                                <li style="margin-bottom: 5px;">MÃ³dulo externo de controles</li>\n                                                <li style="margin-bottom: 5px;">Variador Schneider</li>\n                                                <li style="margin-bottom: 5px;">Variador Danfoss</li>\n                                                <li style="margin-bottom: 5px;">Variador ABB</li>\n                                                <li style="margin-bottom: 5px;">Variador Delta</li>\n                                                <li style="margin-bottom: 5px;">Variador Siemens</li>\n                                                <li style="margin-bottom: 5px;">Variador Allen Bradley</li>\n                        </ul>\n                    </li>\n                </ul>';
    $programacion_variadores = '<div class="schedule-box" style="margin-bottom: 15px;">\n                                        <h5>ð\x9f\x8c\x8e VIRTUAL Perú, Ecuador y otros paÃ\xadses AGOSTO</h5>\n                                        <ul style="margin-bottom: 0;">\n                                            <li><strong>20/08:</strong> Zoom en VIVO de 7:00 p.m. a 9:00 p. m.</li>\n                                            <li><strong>21/08:</strong> SesiÃ³n virtual asíncrona</li>\n                                            <li><strong>22/08:</strong> Zoom en VIVO de 9:00 a.m. a 11:00 a.m. (BLOQUE 1)</li>\n                                            <li><strong>22/08:</strong> Zoom en VIVO de 11:00 a.m. a 1:00 p.m. (BLOQUE 2)</li>\n                                            <li><strong>29/08:</strong> Zoom en VIVO de 9:00 a.m. a 11:00 a.m.(BLOQUE 1)</li>\n                                            <li><strong>29/08:</strong> Zoom en VIVO de 11:00 a.m. a 1:00 p.m. (BLOQUE 2)</li>\n                                            <li><strong>05/09:</strong> Zoom en VIVO de 9:00 a.m. a 11:00 a.m. (BLOQUE 1)</li>\n                                            <li><strong>05/09:</strong> Zoom en VIVO de 11:00 a.m. a 1:00 p.m. (BLOQUE 2)</li>\n                                        </ul>';
    $update = $pdo->prepare("UPDATE cursos SET resumen = ?, temas = ?, beneficios = ?, programacion = ? WHERE LOWER(nombre_curso) LIKE ?");
    $update->execute([$resumen_variadores, $temas_variadores, $beneficios_variadores, $programacion_variadores, '%variadores%']);
    $actualizados += $update->rowCount();

    $resumen_electricidad_industrial = '<p><strong>Duración:</strong> 40 horas académicas</p>\n                <p><strong>Modalidad:</strong> 100% Virtual (En vivo y Asíncrono)</p>\n                <p><strong>Incluye:</strong> Certificado de participación.</p>\n                <p style="margin-top: 10px;">Curso enfocado en brindar los conocimientos y habilidades necesarios para el trabajo en el sector elÃ©ctrico industrial, abarcando desde los fundamentos hasta el mantenimiento de sistemas y automatizaciÃ³n.</p>';
    $temas_electricidad_industrial = '<ul>\n                    <li>Fundamentos teóricos y normativos</li>\n                    <li>Equipos de protección y maniobra</li>\n                    <li>Procedimientos de trabajo seguro (5 reglas de oro)</li>\n                    <li>Mantenimiento preventivo y correctivo</li>\n                    <li>Protocolos de pruebas y elaboración de informes técnicos</li>\n                </ul>';
    $beneficios_electricidad_industrial = '<ul class="list-unstyled" style="padding-left: 10px; margin-bottom: 0;">\n                    <li style="margin-bottom: 8px;"><i class="fas fa-check-circle" style="color: #10b981; margin-right: 8px;"></i>Acceso de por vida al material.</li>\n                    <li style="margin-bottom: 8px;"><i class="fas fa-check-circle" style="color: #10b981; margin-right: 8px;"></i>Soporte directo del docente.</li>\n                    <li style="margin-bottom: 8px;"><i class="fas fa-check-circle" style="color: #10b981; margin-right: 8px;"></i>Material de estudio descargable.</li>\n                    <li style="margin-bottom: 8px;"><i class="fas fa-check-circle" style="color: #10b981; margin-right: 8px;"></i>Certificado de participación.</li>\n                </ul>';
    $programacion_electricidad_industrial = '<div class="schedule-box" >\n                    <h5>ð\x9f\x87µð\x9f\x87ª Virtual Perú</h5>\n                    <ul style="margin-bottom: 5px;">\n                        <li><strong>Horario:</strong> Por definir</li>\n                    </ul>';
    $update = $pdo->prepare("UPDATE cursos SET resumen = ?, temas = ?, beneficios = ?, programacion = ? WHERE LOWER(nombre_curso) LIKE ?");
    $update->execute([$resumen_electricidad_industrial, $temas_electricidad_industrial, $beneficios_electricidad_industrial, $programacion_electricidad_industrial, '%electricidad industrial%']);
    $actualizados += $update->rowCount();

    echo "<h1>Migración de HTML Completa</h1>";
    echo "<p>Se actualizaron los textos descriptivos de los cursos en la BD.</p>";
    echo "<p>Cursos actualizados: $actualizados</p>";
} catch (PDOException $e) {
    echo 'Error: ' . $e->getMessage();
}
