name: Deploy Shopping Cart to cPanel

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Obtener el código
        uses: actions/checkout@v4

      - name: 🚀 Subir a cPanel por SFTP o FTP
        uses: wangyucode/sftp-upload-action@v3
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_KEY }}
          localDir: '.'
          remoteDir: 'public_html'
          exclude: '.git/**,.github/**'
